### ISSUE TITLE
"Serious Warning" on startup - "Subtype has no name: PartSubtype"

### ISSUE THREAD

**Issue by AndersDotExe** [blowfishpro/B9PartSwitch#113]
When launching the game, I get this warning:

![b9 serious warning](https://user-images.githubusercontent.com/35945491/47697510-9a17e700-dbc8-11e8-9b94-22f4ac97cefc.jpg)

The game does seem to function fine after loading, however.

Relevant portion of the log file:

> PartLoader: Compiling Part 'NearFutureConstruction/Parts/Truss/truss-spinal/truss-spinal-01/truss-spinal-01'
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 

> (Filename: Line: 481)

> Warning on PartSubtype: Subtype has no name
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> Warning on PartSubtype: Subtype has no name
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> Warning on PartSubtype: Subtype has no name
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
 
> (Filename:  Line: 481)

> [ERROR] [Part truss-spinal-01] [ModuleB9PartSwitch 'meshSwitch3'] Duplicate subtype names detected: System.String[]
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> Warning on PartSubtype: Subtype has no name
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> Warning on PartSubtype: Subtype has no name
 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

> Warning on PartSubtype: Subtype has no name

I can provide the full log if you want it, should I also bring this up with NearFutureConstuction?

**Comment by blowfishpro** [comment]
This is intended.  It's bad data that should be fixed and could potentially break something (even if it's not apparent that something is broken).  As far as I know it's already being fixed in Near Future.

**Comment by TangentFoxy** [comment]
My install of CKAN just reinstalled Near Future Construction and now this bug is appearing, except it doesn't specify a part. I've narrowed it down to that mod afaik by uninstalling and reinstalling it - this only appears with Near Future Construction installed - but that mod hasn't been updated since December 2020, so I don't understand how it just broke on an install that was only created less than a week ago.

I have no idea how to work out what's going on.

The log has `[ERR 01:33:03.858] [ERROR] [Part truss-spinal-01] [ModuleB9PartSwitch 'meshSwitch3'] Duplicate subtype names detected: ` with a blank line following it, so it seems similar.

Edit: Unfortunately, I do not remember how I fixed this, but after uninstalling and reinstalling mods and restarting a handful of times, it disappeared. No idea how or why.
