### ISSUE TITLE
B9 part switch serious warning

### ISSUE THREAD

**Issue by ysu2** [blowfishpro/B9PartSwitch#142]
I'm getting a bunch of warnings every time I start ksp.   I'm not sure what this refers to, the error messages are rather cryptic to me.  I'm using ckan to intall & manage modes.
windows 7 x64
ksp 1.7 (latest), and latest b9 part switch, installed by - I think - the near-future extensions as dependency.

Any help is appreciated.

![b9partswitch serious warning](https://user-images.githubusercontent.com/5874281/56453165-415c2680-6381-11e9-91a1-4dc800b5be52.png)

**Comment by blowfishpro** [comment]
It's warning of configuration errors on various parts that use B9PartSwitch.  These were all issues previously, the change is that it's displaying the dialog with them rather than just dumping them to the log.  These are all coming from Near Future Construction, I believe Nertea is working of fixing them.  Until that happens you can just click through it though - it's not like any of this was working before anyway.  But if you install additional mods and see additional warnings it might be worth looking into them so that the respective mod authors can be alerted.

**Comment by ysu2** [comment]
I see, thanks!
